### PR TITLE
test: add .travis.yml

### PR DESCRIPTION
**Pull request by brauner**
Signed-off-by: Christian Brauner <christian.brauner@ubuntu.com>

### CODE REVIEW

**Comment by brauner** [comment]
@stgraber

**Comment by brauner** [comment]
I don't expect this to work out of the box.

**Comment by stgraber** [comment]
@brauner I've enabled it in Travis now, try amending your commit and force push, that should be enough to trigger it for this pull request.

**Comment by caglar10ur** [comment]
@brauner travis is failing on other PRs cause it is enabled but there is no .travis.yml file in the repo. Is there a reason not to merge this?

**Comment by brauner** [comment]
@caglar10ur, hm, it's untested from my side so far, that's the only reason.

**Comment by stgraber** [comment]
Lets merge and fix things if needed later.

**Pull request merged**
