### PR TITLE
Add support for additional groups ids on attach.

### PR DESCRIPTION
**Pull request by r10r**
This is the counterpart for https://github.com/lxc/lxc/pull/3575.

### CODE REVIEW

**Comment by stgraber** [comment]
This is going to need some ifdef logic in there so go-lxc can still build with older liblxc

**Comment by r10r** [comment]
hi @stgraber  - I wonder how to do this correctly.
* What do you recommend ?
* Can you point me to a similar implementation ? 
* How to handle the conditional implementation within the go code (`struct_lxc_groups_t`) ?

**Comment by stgraber** [comment]
It's really just the attach_options.groups assignments in the C binding that need to be under ifdef, the rest should be fine.

**Comment by r10r** [comment]
@stgraber This should be it.

**Comment by r10r** [comment]
Hmm, the build did not pick up my last commit. 
I had a look at the build history .. seems that the build job must be fixed.
Last successful build was two years ago ?

**Comment by stgraber** [comment]
Usually the way we do this is with `#if VERSION_AT_LEAST(4, 1, 0)` which will then only compile this code when built against liblxc master or the upcoming 4.1 release.

**Comment by r10r** [comment]
Ok - didn't know that. But how do I then build with this enabled against my development branch / upstream master?

**Comment by r10r** [comment]
What about the CI builds - did I break it or was it broken before?

**Comment by r10r** [comment]
So 4.1.x is the next stable branch ? Is it based on the stable-4.0 branch ?

**Comment by stgraber** [comment]
`4.1` should be the next version outside of the LTS branch. `stable-4.0` is only bugfixes so wouldn't get this change.

**Comment by stgraber** [comment]
Travis was broken before, don't worry about it. We'll just want the liblxc side to be reviewed by @brauner and merged, then this can be merged.

**Comment by r10r** [comment]
Ok - I'm relieved ;) Is there an approximate release date for `4.1` ?

**Comment by r10r** [comment]
> Ok - didn't know that. But how do I then build with this enabled against my development branch / upstream master?

Ok I got it .

**Comment by r10r** [comment]
Just a note to myself: The build  should work once https://github.com/lxc/lxc/pull/3575 is merged.

**Comment by brauner** [comment]
Pulling this now to tweak a few things.

**Comment by brauner** [comment]
> Pulling this now to tweak a few things.

Whoops. wrong repo. :)

**Comment by brauner** [comment]
re-kicking build now

**Comment by r10r** [comment]
hmm, i don't get it - trying locally instead of bugging  Travis.

**Comment by r10r** [comment]
@brauner can you please have a look at the build output - apparently compilation is fixed now but the build still fails.  
Looking at the previous builds indicates that it was already broken.

**Comment by stgraber** [comment]
The tests are known to be complete crap on go-lxc sadly...

I've got a task to both move them to Github Actions and make sure they're vaguely useful but it's very very far down the priority list unfortunately.

**Comment by r10r** [comment]
Ok. I plan to up CI/CD for crio-lxc as well and will take a look at Github Actions. 

Thanks for merging!

**Pull request merged**
