### PR TITLE
introduce TemplateOptions

### PR DESCRIPTION
**Pull request by caglar10ur**

### CODE REVIEW

**Comment by caglar10ur** [comment]
@dcramer, just a heads up. I'm planning to merge this and I think you will need something like following for changes-client (only compile-tested)

Please let me know if you don't want me to break the v2 API or don't like the TemplateOptions

```
diff --git a/adapter/lxc/adapter_test.go b/adapter/lxc/adapter_test.go
index 0cefd54..c731b33 100644
--- a/adapter/lxc/adapter_test.go
+++ b/adapter/lxc/adapter_test.go
@@ -3,13 +3,14 @@
 package lxcadapter

 import (
-       "github.com/dropbox/changes-client/client"
-       "github.com/dropbox/changes-client/client/adapter"
-       "gopkg.in/lxc/go-lxc.v2"
        "log"
        "sync"
        "testing"

+       "github.com/dropbox/changes-client/client"
+       "github.com/dropbox/changes-client/client/adapter"
+       "gopkg.in/lxc/go-lxc.v2"
+
        . "gopkg.in/check.v1"
 )

@@ -33,7 +34,7 @@ func (s *AdapterSuite) reportLogChunks(clientLog *client.Log) {
 func (s *AdapterSuite) ensureContainerRemoved(c *C) {
        container, err := lxc.NewContainer(containerName, lxc.DefaultConfigPath())
        c.Assert(err, IsNil)
-       defer lxc.PutContainer(container)
+       defer lxc.Release(container)

        if container.Running() {
                err = container.Stop()
diff --git a/adapter/lxc/cmd_wrapper.go b/adapter/lxc/cmd_wrapper.go
index 0776eab..b145b9c 100644
--- a/adapter/lxc/cmd_wrapper.go
+++ b/adapter/lxc/cmd_wrapper.go
@@ -5,14 +5,15 @@ package lxcadapter
 import (
        "bytes"
        "fmt"
-       "github.com/dropbox/changes-client/client"
-       "gopkg.in/lxc/go-lxc.v2"
        "io"
        "log"
        "os"
        "path"
        "strings"
        "sync"
+
+       "github.com/dropbox/changes-client/client"
+       "gopkg.in/lxc/go-lxc.v2"
 )

 type LxcCommand struct {
@@ -91,9 +92,9 @@ func (cw *LxcCommand) Run(captureOutput bool, clientLog *client.Log, container *

        log.Printf("[lxc] Executing %s from [%s]", cmdAsUser, cwd)
        ok, err := container.RunCommand(cmdAsUser, &lxc.AttachOptions{
-               Stdinfd:  inwriter.Fd(),
-               Stdoutfd: cmdwriterFd,
-               Stderrfd: cmdwriterFd,
+               StdinFd:  inwriter.Fd(),
+               StdoutFd: cmdwriterFd,
+               StderrFd: cmdwriterFd,
                Env:      env,
                Cwd:      cwd,
        })
diff --git a/adapter/lxc/container.go b/adapter/lxc/container.go
index a9af13d..58baaa0 100644
--- a/adapter/lxc/container.go
+++ b/adapter/lxc/container.go
@@ -6,13 +6,14 @@ import (
        "crypto/rand"
        "errors"
        "fmt"
-       "github.com/dropbox/changes-client/client"
-       "gopkg.in/lxc/go-lxc.v2"
        "log"
        "os"
        "path"
        "strings"
        "time"
+
+       "github.com/dropbox/changes-client/client"
+       "gopkg.in/lxc/go-lxc.v2"
 )

 type Container struct {
@@ -52,11 +53,16 @@ func (c *Container) Launch(clientLog *client.Log) error {
                        if err != nil {
                                return err
                        }
-                       defer lxc.PutContainer(base)
+                       defer lxc.Release(base)
+
+                       options := lxc.DownloadTemplateOptions
+                       options.Arch = c.Arch
+                       options.Release = c.Release
+                       options.Distro = c.Dist
+                       options.Variant = c.Snapshot

                        log.Print("[lxc] Creating base container")
-                       err = base.Create("download", "--arch", c.Arch, "--release", c.Release,
-                               "--dist", c.Dist, "--variant", c.Snapshot)
+                       err = base.Create(options)
                        if err != nil {
                                return err
                        }
@@ -66,7 +72,7 @@ func (c *Container) Launch(clientLog *client.Log) error {
                        if err != nil {
                                return err
                        }
-                       defer lxc.PutContainer(base)
+                       defer lxc.Release(base)
                }

                clientLog.Writeln(fmt.Sprintf("==> Overlaying container: %s", c.Snapshot))
@@ -82,13 +88,21 @@ func (c *Container) Launch(clientLog *client.Log) error {
                if err != nil {
                        return err
                }
-               defer lxc.PutContainer(base)
+               defer lxc.Release(base)

                clientLog.Writeln("==> Creating container")
                if os.Geteuid() != 0 {
-                       err = base.CreateAsUser(c.Dist, c.Release, c.Arch)
+                       options := lxc.DownloadTemplateOptions
+                       options.Release = c.Release
+                       options.Distro = c.Dist
+                       options.Arch = c.Arch
+                       err = base.Create(options)
                } else {
-                       err = base.Create(c.Dist, "--release", c.Release, "--arch", c.Arch)
+                       options := lxc.UbuntuTemplateOptions
+                       options.Template = c.Dist
+                       options.Release = c.Release
+                       options.Arch = c.Arch
+                       err = base.Create(options)
                }
                if err != nil {
                        return err
@@ -190,7 +204,7 @@ func (c *Container) Destroy() error {
                return nil
        }

-       defer lxc.PutContainer(c.lxc)
+       defer lxc.Release(c.lxc)

        c.Stop()

@@ -423,7 +437,6 @@ func (c *Container) createImageSnapshotID(snapshotPath string, clientLog *client
        return nil
 }

-
 func (c *Container) UploadImage(snapshot string, clientLog *client.Log) error {
        relPath := c.getImagePath(snapshot)
        localPath := fmt.Sprintf("/var/cache/lxc/download/%s", relPath)
```

**Comment by caglar10ur** [comment]
Actually I just realized even right now (before merging this) changes-client needs this to compile

```
diff --git a/adapter/lxc/cmd_wrapper.go b/adapter/lxc/cmd_wrapper.go
index 0776eab..2b76718 100644
--- a/adapter/lxc/cmd_wrapper.go
+++ b/adapter/lxc/cmd_wrapper.go
@@ -91,9 +91,9 @@ func (cw *LxcCommand) Run(captureOutput bool, clientLog *client.Log, container *

        log.Printf("[lxc] Executing %s from [%s]", cmdAsUser, cwd)
        ok, err := container.RunCommand(cmdAsUser, &lxc.AttachOptions{
-               Stdinfd:  inwriter.Fd(),
-               Stdoutfd: cmdwriterFd,
-               Stderrfd: cmdwriterFd,
+               StdinFd:  inwriter.Fd(),
+               StdoutFd: cmdwriterFd,
+               StderrFd: cmdwriterFd,
                Env:      env,
                Cwd:      cwd,
        })
diff --git a/adapter/lxc/container.go b/adapter/lxc/container.go
index a9af13d..a6bbd33 100644
--- a/adapter/lxc/container.go
+++ b/adapter/lxc/container.go
@@ -52,7 +52,7 @@ func (c *Container) Launch(clientLog *client.Log) error {
                        if err != nil {
                                return err
                        }
-                       defer lxc.PutContainer(base)
+                       defer lxc.Release(base)

                        log.Print("[lxc] Creating base container")
                        err = base.Create("download", "--arch", c.Arch, "--release", c.Release,
@@ -66,7 +66,7 @@ func (c *Container) Launch(clientLog *client.Log) error {
                        if err != nil {
                                return err
                        }
-                       defer lxc.PutContainer(base)
+                       defer lxc.Release(base)
                }

                clientLog.Writeln(fmt.Sprintf("==> Overlaying container: %s", c.Snapshot))
@@ -82,7 +82,7 @@ func (c *Container) Launch(clientLog *client.Log) error {
                if err != nil {
                        return err
                }
-               defer lxc.PutContainer(base)
+               defer lxc.Release(base)

                clientLog.Writeln("==> Creating container")
                if os.Geteuid() != 0 {
@@ -190,7 +190,7 @@ func (c *Container) Destroy() error {
                return nil
        }

-       defer lxc.PutContainer(c.lxc)
+       defer lxc.Release(c.lxc)

        c.Stop()
```

sorry for the inconvenience...

**Comment by dcramer** [comment]
No worries. I do think something might have changed that creates a backwards incompatibility (beyond the APIs themselves). I'm looking into it and will let you know.

fwiw the behavior I'm seeing is the "copy a file into the rootfs folder and then execute it" feature is no longer working, in the sense that the container appears to not see the file that was placed there. I'm not super familiar with LXC, but I'm sure its something simple.

**Comment by dcramer** [comment]
Found it.

Had to specify Namespaces: -1

**Comment by caglar10ur** [comment]
Hmm yeah DefaultAttachOptions ( https://github.com/lxc/go-lxc/pull/19/files#diff-4aae454123f50b906f9aaef44f10011eR51 ) provides that, sometimes I really don't like the "zero values" of variables. 

At some point I thought using pointer types so that I can check them against nil to see whether they are set or not but that requires helper functions like goprotobuf (http://godoc.org/code.google.com/p/goprotobuf/proto#Int)

**Comment by dcramer** [comment]
Yeah I dont have a good solution. I think as long as you realize that "if you override any options you must be explicit about them all" you are ok. I dont think there's a really good pattern to somehow merge the defaults with the custom options.

What about a MakeAttachOptions (or similar) which returns the defaults, and then you can override them?

**Comment by caglar10ur** [comment]
That's why I had DefaultAttachOptions. I was thinking usage could be like https://github.com/lxc/go-lxc/blob/v2/examples/attach.go#L38

**Comment by dcramer** [comment]
Wouldn’t that override the defaults though (rather than cloning them)

**Comment by dcramer** [comment]
I believe the only other issues I've noticed between Python and Go now is a change in how /dev is processed.

Basically `echo '1' > /dev/stdout worked` on our Python implementation, but we hit a permission denied on the Go implementation.

I'll keep searching and let you know when I find the reason.

**Comment by dcramer** [comment]
Actually I'm told this is apparmor related, and I'm going to make an assumption its because SetConfigItem doesnt replace, but it appends.

**Comment by dcramer** [comment]
Just to follow up, I've at least confirmed that ConfigItem("lxc.aa_profile") seems to be set correctly. Going to dig some more.

**Comment by caglar10ur** [comment]
I see what you are saying about overriding v.s. cloning, that's because we are passing a pointer instead. We could just do something like following for creating the effect that you want;

```
diff --git a/container.go b/container.go
index 3bd1d5b..857c5d6 100644
--- a/container.go
+++ b/container.go
@@ -1003,7 +1003,7 @@ func (c *Container) Console(options *ConsoleOptions) error {

 // AttachShell attaches a shell to the container.
 // It clears all environment variables before attaching.
-func (c *Container) AttachShell(options *AttachOptions) error {
+func (c *Container) AttachShell(options AttachOptions) error {
        if err := c.makeSure(isDefined | isRunning); err != nil {
                return err
        }
@@ -1048,7 +1048,7 @@ func (c *Container) AttachShell(options *AttachOptions) error {
 // RunCommand attachs a shell and runs the command within the container.
 // The process will wait for the command to finish and return a success status. An error
 // is returned only when invocation of the command completely fails.
-func (c *Container) RunCommand(args []string, options *AttachOptions) (bool, error) {
+func (c *Container) RunCommand(args []string, options AttachOptions) (bool, error) {
        if len(args) == 0 {
                return false, ErrInsufficientNumberOfArguments
        }
diff --git a/options.go b/options.go
index ddb0afd..85c2da2 100644
--- a/options.go
+++ b/options.go
@@ -48,7 +48,7 @@ type AttachOptions struct {
 }

 // DefaultAttachOptions is a convenient set of options to be used.
-var DefaultAttachOptions = &AttachOptions{
+var DefaultAttachOptions = AttachOptions{
        Namespaces: -1,
        Arch:       -1,
        Cwd:        "/",
```

Do you see any problem here, if not I'll change the code

**Comment by caglar10ur** [comment]
About the "permission denied" problem. I haven't tried the python binding but using regular lxc tools also ends up with same result (lxc-create followed by lxc-attach)

```
lxc-attach -n rubik
root@rubik:/# echo '1' > /dev/stdout
bash: /dev/stdout: Permission denied
root@rubik:/#
```

so I'm not sure what python is doing different. Will try that but maybe you can create a new issue for that, so that we can track it independently

**Comment by dcramer** [comment]
@caglar10ur I'm going to investigate more, but supposedly aa_profile should resolve /dev/std*, so something must not be applying in the same fashion. I'll follow up if I find it's something internal to go-lxc

**Comment by caglar10ur** [comment]
Converted *{Attach|TemplateOptions} to {Attach|Template}Options, merging now...

**Pull request merged**
