### PR TITLE
Fixed undefined: go_lxc_config_item_is_supported

### PR DESCRIPTION
**Pull request by soffokl**
image

### CODE REVIEW

**Comment by soffokl** [comment]
@stgraber @brauner Looks like https://github.com/lxc/go-lxc/commit/0a9c896303e8734f97c8b7e6357204cfd946fd4b brakes build. This PR should fix it.

**Comment by brauner** [comment]
@soffokl, you need to sign-off your commit for us to include it. Should be as simple as doing:

    git commit --amend -s

**Comment by soffokl** [comment]
@brauner seems done.

**Comment by brauner** [comment]
@soffokl, cool thanks!

**Comment by brauner** [comment]
@caglar10ur, care to merge this real quick?

**Comment by brauner** [comment]
What do:

    hciconfig
    hcitool scan
    hcitool dev

inside the container show?

**Comment by stgraber** [comment]
@brauner wrong issue it looks like :)

**Comment by brauner** [comment]
Dammit. :)

**Pull request merged**
